-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 
-- 이때 결과는 보호 시작일이 빠른 순으로 조회해야합니다.

-- 1
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID
AND A.DATETIME >= B.DATETIME
ORDER BY A.DATETIME DESC;

-- 2
SELECT B.ANIMAL_ID, B.NAME, A.DATETIME
FROM ANIMAL_INS A INNER JOIN ANIMAL_OUTS B
ON (A.ANIMAL_ID = B.ANIMAL_ID 
AND A.DATETIME > B.DATETIME)
ORDER BY A.DATETIME ASC;
